/**
 * "AI daily report" card: a plain-language Gemini-generated summary of the selected
 * station's water-quality stats since local midnight (see main.py's `_generate_ai_report`
 * and its midnight scheduler). Polled slowly since the value only changes once a day
 * under normal operation; a live `ai_report` WS event (see useSensorSocket's `lastAiReport`)
 * refreshes it immediately for every connected dashboard, not just the one that triggered it.
 *
 * The "Generate now" button is admin-only (see RoleProvider.tsx) so a demo doesn't have to
 * wait for real midnight -- same UI-only gating precedent as StationSwitcher's rename button,
 * NOT backend-enforced authentication.
 */
import { useEffect } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Sparkles } from 'lucide-react'
import { toast } from 'sonner'
import { ApiError, generateAiReport, getAiReport } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { useT } from '@/lib/i18n'
import { useRole } from '@/lib/RoleProvider'
import { useSensorData } from '@/lib/SensorProvider'

const REFETCH_INTERVAL_MS = 5 * 60_000

interface AiReportCardProps {
  /** Selected station -- see DashboardView/StationSwitcher. */
  station: string
}

export function AiReportCard({ station }: AiReportCardProps) {
  const { t } = useT()
  const { role } = useRole()
  const { lastAiReport } = useSensorData()
  const queryClient = useQueryClient()
  const queryKey = ['ai-report', station] as const

  const { data, isLoading, isError, error } = useQuery({
    queryKey,
    queryFn: () => getAiReport(station),
    refetchInterval: REFETCH_INTERVAL_MS,
    retry: false,
  })

  // A live ai_report WS event for this station (generated by the midnight scheduler, or by
  // any connected dashboard's "Generate now" click) -- refetch instead of trusting the event
  // payload directly, so this stays the single source of truth main.py's GET /ai-report agrees with.
  useEffect(() => {
    if (lastAiReport && lastAiReport.station === station) {
      void queryClient.invalidateQueries({ queryKey })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lastAiReport?.at])

  const generateMutation = useMutation({
    mutationFn: () => generateAiReport(station),
    onSuccess: (result) => {
      // `cached` means the backend's per-station cooldown was still active -- this click
      // didn't spend a Gemini request, it just got back the same report an earlier click (by
      // this admin or any other) already generated. Said plainly so repeated clicks during a
      // demo don't look like the button is silently broken.
      toast.success(result.cached ? t('aiReport.generateCached') : t('aiReport.generateSuccess'))
      void queryClient.invalidateQueries({ queryKey })
    },
    onError: () => toast.error(t('aiReport.generateFailed')),
  })

  // Not configured on the backend at all (no Gemini key) -- distinct from "configured but no
  // report yet", and distinct enough from every other error to warrant its own quiet message
  // rather than a scary "failed" toast-style banner on every page load.
  const notConfigured = isError && error instanceof ApiError && error.status === 503

  return (
    <Card data-tour="ai-report">
      <CardHeader className="flex flex-row items-center justify-between gap-3 space-y-0">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" aria-hidden="true" />
          <CardTitle className="text-base">{t('aiReport.title')}</CardTitle>
        </div>
        {role === 'admin' && !notConfigured && (
          <Button
            type="button"
            variant="outline"
            size="sm"
            disabled={generateMutation.isPending}
            onClick={() => generateMutation.mutate()}
          >
            {generateMutation.isPending ? t('aiReport.generating') : t('aiReport.generateNow')}
          </Button>
        )}
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <Skeleton className="h-16 w-full" />
        ) : notConfigured ? (
          <p className="text-sm text-muted-foreground">{t('aiReport.notConfigured')}</p>
        ) : isError ? (
          <p className="text-sm text-destructive">{t('aiReport.loadFailed')}</p>
        ) : data?.report ? (
          <div className="space-y-1">
            <p className="whitespace-pre-line text-sm text-foreground">{data.report}</p>
            {data.date && (
              <p className="text-xs text-muted-foreground">{t('aiReport.lastGenerated', { date: data.date })}</p>
            )}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">{t('aiReport.empty')}</p>
        )}
      </CardContent>
    </Card>
  )
}
