/**
 * Single UI-text catalogue for the Aqua Monitor frontend. Every user-facing
 * string in the app lives here as a flat dot-key -> string map, in both `en`
 * and `th`, with identical key sets. No logic, no JSX, just text.
 *
 * Copy conventions:
 * - Short labels and buttons have no trailing period; full sentences do.
 * - Ellipses are three ASCII dots, never the single-character ellipsis.
 * - No em or en dashes anywhere. Use a period, comma, or parentheses instead.
 * - Language names are written natively ("English", "ไทย") in both locales.
 *
 * Interpolation: use `{placeholder}` tokens, resolved by `useT().t(key, vars)`
 * in lib/i18n.tsx, e.g. t('detail.dataPoints', { count: 42 }).
 */

export type Lang = 'en' | 'th'

const en = {
  // --- nav ---------------------------------------------------------------
  'nav.dashboard': 'Dashboard',
  'nav.calibration': 'Calibration',
  'nav.history': 'History',
  'nav.expandMenu': 'Expand menu',

  // --- app shell -----------------------------------------------------------
  'app.title': 'Aqua Monitor',
  'app.siteName': 'Ang Kaew Reservoir',
  'app.siteNameShort': 'Ang Kaew',
  'app.subtitle': 'Chiang Mai University',

  // --- stations --------------------------------------------------------------
  /** Friendly label for the "default" station sentinel -- shown instead of the
   * literal word "default" whenever a board has no custom station name set. */
  'station.defaultLabel': 'Main Station',
  'station.switcherLabel': 'Station',
  'station.rename': 'Rename station',
  'station.renameLabel': 'Station name',
  'station.renameWarning':
    "This only renames it here. The board itself still reports the old name and will start a new, uncalibrated station under it next time it reports, unless you also reprovision the board's name over USB.",
  'station.renameSuccess': 'Station renamed.',
  'station.renameFailedCollision': 'A station with that name already exists.',
  'station.renameFailedNotFound': 'That station no longer exists.',
  'station.renameFailedGeneric': 'Failed to rename station.',
  'station.renameCancel': 'Cancel',
  'station.renameSave': 'Save',

  // --- user ----------------------------------------------------------------
  'user.guest': 'Guest',
  'user.role': 'View only',
  'user.admin': 'Admin',
  'user.roleAdmin': 'Full access',
  'user.switchToAdmin': 'Switch to Admin',
  'user.switchToGuest': 'Switch to Guest',

  // --- status ----------------------------------------------------------------
  'status.good': 'Good',
  'status.caution': 'Caution',
  'status.danger': 'Danger',
  'status.unknown': 'Unknown',
  'status.safe': 'Safe',
  'status.online': 'Online',
  'status.offline': 'Offline',
  'status.noData': 'No data',
  'status.notConnected': 'Not connected',

  // --- history/chart time range --------------------------------------------
  'window.5m': '5 min',
  'window.15m': '15 min',
  'window.1h': '1 hour',
  'window.3h': '3 hours',
  'window.12h': '12 hours',
  'window.24h': '24 hours',
  'window.label': 'Time range',

  // --- parameters ------------------------------------------------------------
  'param.temperature.label': 'Temperature',
  'param.temperature.about':
    'Water temperature sets how much oxygen the water can hold and how fast aquatic life uses it.',
  'param.temperature.impact':
    'Readings outside the normal range stress fish and other aquatic life, and can speed up algae growth.',
  'param.temperature.recommendation':
    'Check the shading, the inflow, and whether the probe has shifted. Watch the next few readings before acting.',

  'param.turbidity.label': 'Turbidity',
  'param.turbidity.fullName': 'Turbidity',
  'param.turbidity.about':
    'Turbidity is a measure of the particles suspended in the water, which limit how far light reaches.',
  'param.turbidity.impact':
    'High turbidity keeps sunlight from reaching aquatic plants. It often points to runoff, stirred sediment, or an algae bloom.',
  'param.turbidity.recommendation':
    'Check for recent rain or upstream disturbance. If the reading stays high, clean the sensor lens.',

  'param.tds.label': 'TDS',
  'param.tds.fullName': 'Total Dissolved Solids',
  'param.tds.about':
    'Total dissolved solids is the amount of minerals and salts dissolved in the water, measured in parts per million.',
  'param.tds.impact':
    'TDS outside the normal range can change the taste of the water, point to contamination, or stress freshwater life.',
  'param.tds.recommendation':
    'Compare it against the recent trend. If the reading is unusually high, check for runoff or discharge nearby.',

  'param.ec.label': 'EC',
  'param.ec.fullName': 'Electrical Conductivity',
  'param.ec.about':
    'Electrical conductivity comes from the ions dissolved in the water, so it tracks closely with TDS.',
  'param.ec.impact':
    'An unusual EC reading means the dissolved salts or minerals have changed, which can point to pollution or mineral runoff.',
  'param.ec.recommendation':
    'Check the TDS reading too, since EC is derived from it. A sudden change in both is worth investigating.',

  'param.flow.label': 'Flow',
  'param.flow.about': 'Instantaneous flow rate through the sensor, in liters per minute.',

  // --- units ---------------------------------------------------------------
  'unit.ntu.fullName': 'Nephelometric Turbidity Units',
  'unit.ppm.fullName': 'parts per million',
  'unit.ecUnit.fullName': 'microsiemens per centimeter',

  // --- parameter detail modal ------------------------------------------------
  'detail.currentValue': 'Current value',
  'detail.noRecord': 'No readings yet',
  'detail.dataPoints': '{count} data points',
  'detail.min': 'Min',
  'detail.avg': 'Avg',
  'detail.max': 'Max',
  'detail.tooHigh': '{param} is above the safe range ({value} {unit})',
  'detail.tooLow': '{param} is below the safe range ({value} {unit})',
  'detail.checkSensor': 'This reading is too low to be real. Check the sensor rather than the water.',
  'detail.normalRange': 'Normal range: {range}',
  'detail.aboutTitle': 'About',
  'detail.impactTitle': 'Impact',
  'detail.recommendationTitle': 'Recommendation',
  'detail.chartCaption': 'Live sensor data. Pick a time range above.',

  // --- WQI ---------------------------------------------------------------
  'wqi.title': 'Water Quality Index (WQI)',
  'wqi.moderate': 'Moderate',
  'wqi.good': 'Good',
  'wqi.poor': 'Poor',
  'wqi.unknown': 'Unknown',
  'wqi.empty': 'No history yet for this time range.',
  'wqi.error': "Couldn't load history for this time range.",

  // --- flow/usage dashboard charts --------------------------------------------
  'chart.flow.title': 'Water Flow',
  'chart.flow.unit': 'L/min',
  'chart.usage.title': 'Water Usage',
  'chart.usage.unit': 'L',
  'chart.usage.today': 'Today: {value} L',
  'chart.usage.empty': 'No usage data yet.',
  'chart.usage.resetToday': 'Reset today',
  'chart.usage.resetSuccess': "Today's usage reset",
  'chart.usage.resetFailed': "Couldn't reset today's usage",

  // --- quick view (dashboard right column) ----------------------------------
  'quickview.title': 'Quick view',
  'quickview.sensorFault': 'Not connected',
  'quickview.analysis.noData': 'No live sensor data yet.',
  'quickview.analysis.good': 'All readings are within the normal range.',
  'quickview.analysis.watch': '{band} — watch: {params}.',
  'quickview.analysis.fault': 'Check the sensors: {params} may be disconnected.',
  'quickview.flow.label': 'Current flow',
  'quickview.usage.label': "Today's usage",

  // --- calibration ---------------------------------------------------------
  'calib.title': 'Sensor Calibration',
  'calib.subtitle': 'Calibrate while the sensors keep running, without uploading new firmware.',
  'calib.modeLabel': 'Calibration mode',
  'calib.modeOn': 'ON',
  'calib.modeOff': 'OFF',
  'calib.applyingTurbidity': 'Applying turbidity calibration...',
  'calib.applyingTds': 'Applying TDS calibration...',
  'calib.applyingFlow': 'Applying flow calibration...',
  'calib.failedTurbidity': "Couldn't apply the turbidity calibration",
  'calib.failedTds': "Couldn't apply the TDS calibration",
  'calib.failedFlow': "Couldn't apply the flow calibration",
  'calib.resetSuccess': 'Calibration reset',
  'calib.resetFailed': "Couldn't reset",
  'calib.modeChangeFailed': "Couldn't change the mode",
  'calib.temperatureTitle': 'Temperature',
  'calib.noCalibrationNeeded': 'No calibration needed',
  'calib.factoryCalibrated': 'Factory calibrated (DS18B20 ±0.5°C)',
  'calib.ecTitle': 'Electrical Conductivity (EC)',
  'calib.noSeparateSensor': 'No separate sensor',
  'calib.derivedFromTds': 'Derived from TDS (×0.5). Calibrate it through TDS.',
  'calib.resetTurbidity': 'Reset turbidity',
  'calib.resetTds': 'Reset TDS',
  'calib.resetFlow': 'Reset flow',
  'calib.flowFormTitle': 'Flow calibration (k-factor)',
  'calib.flowReferenceLabel': 'Known volume (liters)',
  'calib.flowRawLabel': 'Measured (pulse count)',
  'calib.flowRawHint': 'Run the known volume through the sensor, then enter the total pulses counted.',
  'calib.needFlowPoints': '1 point',
  'calib.flowKFactorFormula': 'Liters = pulses ÷ k (k = pulses per liter)',
  'calib.observedRange': 'Observed while calibrating: {min} min, {max} max',
  'calib.useMin': 'Use min',
  'calib.useMax': 'Use max',
  'calib.resetRange': 'Reset range',
  'calib.loading': 'Loading...',
  'calib.sensorSelectAria': 'Sensor selection',
  'calib.turbidityFormTitle': 'Turbidity calibration (2-point)',
  'calib.turbidityReferenceLabel': 'Standard value (NTU)',
  'calib.turbidityRawLabel': 'Measured (raw ADC)',
  'calib.turbidityRawHint': 'Leave blank to use the live reading',
  'calib.tdsFormTitle': 'TDS calibration (k-factor)',
  'calib.tdsReferenceLabel': 'Known ppm (reference)',
  'calib.tdsRawLabel': 'Measured (ppm, optional)',
  'calib.tdsRawHint':
    'Preview only, never sent to the server. Enter the uncalibrated ppm reading, not the raw voltage.',
  'calib.applyLabel': 'Apply',
  'calib.applying': 'Applying...',
  'calib.needTwoPoints': 'Needs 2 points',
  'calib.singlePoint': 'Single point',
  'calib.liveReading': 'Live reading',
  'calib.pointLabel': 'Point {n}',
  'calib.savedPoints': 'Saved points',
  'calib.deletePoint': 'Delete point',
  'calib.coefficientsTitle': 'Coefficients',
  'calib.pending': 'Unconfirmed',
  'calib.notCalibrated': 'Not calibrated yet',
  'calib.needTurbidityPoints': '2 points',
  'calib.needTdsPoints': '1 point',
  'calib.currentResult': 'Current result',
  'calib.kFactorFormula': 'Calibrated ppm = k × raw DFRobot reading',
  'calib.lastSaved': 'Last saved',

  // --- history table ---------------------------------------------------------
  'history.title': 'History',
  'history.loading': 'Loading...',
  'history.failed': "Couldn't load the data",
  'history.empty': 'No data in this time range',
  'history.exportCsv': 'Export CSV',
  'history.col.time': 'Time',
  'history.col.temperature': 'Temperature (°C)',
  'history.col.turbidity': 'Turbidity',
  'history.col.tds': 'TDS (ppm)',
  'history.col.ec': 'EC (µS/cm)',
  'history.col.status': 'Status',
  'history.rowCount': '{count} readings from {source}',
  'history.refreshing': 'refreshing...',

  // --- common ------------------------------------------------------------
  'common.close': 'Close',
  'common.reload': 'Reload',
  'common.error': 'Something went wrong.',
  'common.openMenu': 'Open menu',
  'common.loading': 'Loading...',
  'common.uncalibrated': 'Uncalibrated (raw ADC)',

  // --- theme ---------------------------------------------------------------
  'theme.toggle': 'Toggle theme',
  'theme.label': 'Theme',
  'theme.light': 'Light',
  'theme.dark': 'Dark',

  // --- language ------------------------------------------------------------
  'lang.switch': 'Switch language',
  'lang.en': 'English',
  'lang.th': 'ไทย',

  // --- guided tour -----------------------------------------------------------
  'tour.welcome.title': 'Welcome to Aqua Monitor',
  'tour.welcome.body': "Let's take a quick look around the dashboard. This will only take a minute.",
  'tour.navDashboard.title': 'Dashboard tab',
  'tour.navDashboard.body': 'The live overview: water quality history, current readings, and safety gauges.',
  'tour.paramGrid.title': 'Live readings',
  'tour.paramGrid.body': 'Temperature, turbidity, TDS, and EC update in real time. Tap any card for details and trends.',
  'tour.quickView.title': 'Quick view',
  'tour.quickView.body': 'A one-glance summary of the overall water quality index and each parameter\'s status.',
  'tour.navCalibration.title': 'Calibration tab',
  'tour.navCalibration.body': 'Calibrate the turbidity and TDS sensors against known reference samples, no reflashing needed.',
  'tour.navHistory.title': 'History tab',
  'tour.navHistory.body': 'Browse past readings over a chosen time range and export them as CSV.',
  'tour.themeToggle.title': 'Theme toggle',
  'tour.themeToggle.body': 'Switch between light and dark mode at any time.',
  'tour.langToggle.title': 'Language',
  'tour.langToggle.body': 'Switch the whole interface between English and Thai.',
  'tour.done.title': "You're all set",
  'tour.done.body': 'Replay this tour anytime from the help button. Enjoy monitoring your water quality.',
  'tour.next': 'Next',
  'tour.back': 'Back',
  'tour.skip': 'Skip',
  'tour.done': 'Done',
  'tour.stepCounter': '{current} / {total}',
  'tour.helpButtonAria': 'Replay guided tour',
  'tour.helpLabel': 'Help',

  // --- notifications ---------------------------------------------------------
  'notif.bellAria': 'Notification settings',
  'notif.title': 'Notifications',
  'notif.description': 'Get notified when a reading enters a warning or danger range, even when this tab is closed.',
  'notif.unsupported': 'Push notifications are not supported in this browser.',
  'notif.insecureContext': 'Push notifications need a secure connection (HTTPS or localhost).',
  'notif.enable': 'Enable notifications',
  'notif.enabling': 'Enabling...',
  'notif.unsubscribe': 'Unsubscribe',
  'notif.unsubscribing': 'Unsubscribing...',
  'notif.prefsTitle': 'Alert me on',
  'notif.subscribeSuccess': 'Notifications enabled',
  'notif.subscribeFailedPermission': 'Notification permission was denied',
  'notif.subscribeFailedUnavailable': 'Push notifications are not configured on the server',
  'notif.subscribeFailed': "Couldn't enable notifications",
  'notif.unsubscribeSuccess': 'Notifications turned off',
  'notif.unsubscribeFailed': "Couldn't turn off notifications",
  'notif.prefsSaveFailed': "Couldn't save notification preferences",
  'notif.sendTest': 'Send test notification',
  'notif.sendingTest': 'Sending...',
  'notif.testSuccess': 'Test notification sent',
  'notif.testFailed': "Couldn't send test notification",

  // --- settings dialog ---------------------------------------------------------
  'settings.bellAria': 'Settings',
  'settings.title': 'Settings',
  'settings.notificationsSection': 'Notifications',
  'settings.displaySection': 'Dashboard display',
  'settings.displayDescription': 'Choose which series show on the main Dashboard.',
  'settings.showWaterUsage': 'Water usage chart',

  // --- wifi provisioning (Calibration tab) ------------------------------------
  'wifi.label': 'WiFi',
  'wifi.title': 'WiFi setup',
  'wifi.description': 'Connect the ESP32 to a network over USB -- no reflashing needed.',
  'wifi.unsupportedBrowser':
    'USB device access needs Chrome, Edge, or another Chromium-based browser (not supported here).',
  'wifi.deviceConnect': 'Connect to board',
  'wifi.deviceConnecting': 'Connecting...',
  'wifi.deviceConnectHint': "Your browser will ask you to pick the board's USB port.",
  'wifi.deviceConnectFailed': "Couldn't connect to the board",
  'wifi.deviceDisconnect': 'Disconnect',
  'wifi.deviceDisconnected': 'Board disconnected',
  'wifi.notConnected': 'Not connected to any network yet.',
  'wifi.currentlyConnected': 'Connected to {ssid} ({ip})',
  'wifi.scan': 'Scan for networks',
  'wifi.scanning': 'Scanning...',
  'wifi.scanFailed': "Couldn't scan for networks",
  'wifi.noNetworks': 'No networks found. Try scanning again.',
  'wifi.passwordLabel': 'Password',
  'wifi.passwordPlaceholder': 'Enter network password',
  'wifi.connect': 'Connect',
  'wifi.connecting': 'Connecting...',
  'wifi.connectSuccess': 'Connected! New IP: {ip}',
  'wifi.connectFailed': "Couldn't connect",
  'wifi.backendTitle': 'Backend on a different network',
  'wifi.backendDescription':
    "By default the board finds the backend by broadcasting on its own network, which only works if the backend PC is on the same network. If it's on a different one, enter the backend's address here (a hostname or IP it's reachable at from the internet or a VPN, e.g. a DDNS name) to point the board at it directly.",
  'wifi.backendCurrentFixed': 'Using fixed backend: {host}',
  'wifi.backendCurrentAuto': 'Using same-network auto-discovery.',
  'wifi.backendHttpsOn': 'HTTPS',
  'wifi.backendKeySet': 'API key set',
  'wifi.backendHostLabel': 'Backend host or IP',
  'wifi.backendHostPlaceholder': 'e.g. myhydro.duckdns.org',
  'wifi.backendApiKeyLabel': 'API key (optional)',
  'wifi.backendApiKeyPlaceholder': 'Leave blank for no authentication',
  'wifi.backendApiKeyHint':
    "Must match the backend's webconfig.json updateApiKey. Required once the backend is reachable from outside your local network -- otherwise anyone who can reach it can post fake readings.",
  'wifi.backendHttpsLabel': 'Use HTTPS (recommended when off the local network)',
  'wifi.backendSave': 'Save',
  'wifi.backendSaving': 'Saving...',
  'wifi.backendClear': 'Clear (use auto-discovery)',
  'wifi.backendSaveSuccess': 'Backend updated',
  'wifi.backendSaveFailed': "Couldn't update the backend",
  'wifi.backendTest': 'Test connection',
  'wifi.backendTesting': 'Testing...',
  'wifi.backendTestSuccess': 'Connected ({detail})',
  'wifi.backendTestUnreachable': "Couldn't reach the backend",
  'wifi.backendTestFailed': "Couldn't run the test",
  'wifi.stationTitle': 'Station name',
  'wifi.stationDescription':
    'A short label for this board (e.g. "Inlet" or "Outlet") so the dashboard can tell several boards apart. Leave unset for a single-board setup.',
  'wifi.stationCurrentSet': 'This board is named: {name}',
  'wifi.stationCurrentUnset': 'No station name set (reports as the main station).',
  'wifi.stationLabel': 'Station name',
  'wifi.stationPlaceholder': 'e.g. Inlet',
  'wifi.stationSave': 'Save',
  'wifi.stationSaving': 'Saving...',
  'wifi.stationClear': 'Clear',
  'wifi.stationSaveSuccess': 'Station name updated',
  'wifi.stationSaveFailed': "Couldn't update the station name",
} as const

export const messages = {
  en,
  th: {
    'nav.dashboard': 'แดชบอร์ด',
    'nav.calibration': 'ปรับเทียบ',
    'nav.history': 'ประวัติ',
    'nav.expandMenu': 'ขยายเมนู',

    'app.title': 'Aqua Monitor',
    'app.siteName': 'อ่างเก็บน้ำอ่างแก้ว',
    'app.siteNameShort': 'อ่างแก้ว',
    'app.subtitle': 'มหาวิทยาลัยเชียงใหม่',

    'station.defaultLabel': 'สถานีหลัก',
    'station.switcherLabel': 'สถานี',
    'station.rename': 'เปลี่ยนชื่อสถานี',
    'station.renameLabel': 'ชื่อสถานี',
    'station.renameWarning':
      'การเปลี่ยนชื่อนี้มีผลเฉพาะที่นี่เท่านั้น บอร์ดยังคงรายงานชื่อเดิม และจะสร้างสถานีใหม่ที่ยังไม่ได้ปรับเทียบภายใต้ชื่อเดิมในครั้งถัดไปที่รายงาน เว้นแต่จะตั้งชื่อบอร์ดใหม่ผ่าน USB ด้วย',
    'station.renameSuccess': 'เปลี่ยนชื่อสถานีแล้ว',
    'station.renameFailedCollision': 'มีสถานีชื่อนี้อยู่แล้ว',
    'station.renameFailedNotFound': 'ไม่พบสถานีนี้แล้ว',
    'station.renameFailedGeneric': 'เปลี่ยนชื่อสถานีไม่สำเร็จ',
    'station.renameCancel': 'ยกเลิก',
    'station.renameSave': 'บันทึก',

    'user.guest': 'ผู้เยี่ยมชม',
    'user.role': 'ดูอย่างเดียว',
    'user.admin': 'ผู้ดูแลระบบ',
    'user.roleAdmin': 'สิทธิ์เต็ม',
    'user.switchToAdmin': 'สลับเป็นผู้ดูแลระบบ',
    'user.switchToGuest': 'สลับเป็นผู้เยี่ยมชม',

    'status.good': 'ดี',
    'status.caution': 'เฝ้าระวัง',
    'status.danger': 'อันตราย',
    'status.unknown': 'ไม่ทราบ',
    'status.safe': 'ปลอดภัย',
    'status.online': 'ออนไลน์',
    'status.offline': 'ออฟไลน์',
    'status.noData': 'ไม่มีข้อมูล',
    'status.notConnected': 'ไม่ได้เชื่อมต่อ',

    'window.5m': '5 นาที',
    'window.15m': '15 นาที',
    'window.1h': '1 ชั่วโมง',
    'window.3h': '3 ชั่วโมง',
    'window.12h': '12 ชั่วโมง',
    'window.24h': '24 ชั่วโมง',
    'window.label': 'ช่วงเวลา',

    'param.temperature.label': 'อุณหภูมิ',
    'param.temperature.about':
      'อุณหภูมิน้ำกำหนดปริมาณออกซิเจนที่น้ำเก็บไว้ได้ และอัตราที่สิ่งมีชีวิตในน้ำใช้ออกซิเจนนั้น',
    'param.temperature.impact':
      'ค่าที่อยู่นอกช่วงปกติสร้างความเครียดให้ปลาและสิ่งมีชีวิตอื่นในน้ำ และอาจเร่งการเติบโตของสาหร่าย',
    'param.temperature.recommendation':
      'ตรวจสอบร่มเงา ทางน้ำเข้า และตำแหน่งของหัววัดว่าขยับหรือไม่ แล้วเฝ้าดูค่าอีกสองสามรอบก่อนดำเนินการ',

    'param.turbidity.label': 'ความขุ่น',
    'param.turbidity.fullName': 'ความขุ่น (Turbidity)',
    'param.turbidity.about':
      'ความขุ่นคือปริมาณอนุภาคที่แขวนลอยอยู่ในน้ำ ซึ่งจำกัดระยะที่แสงส่องลงไปได้',
    'param.turbidity.impact':
      'ความขุ่นสูงบังแสงแดดไม่ให้ส่องถึงพืชน้ำ และมักบ่งชี้น้ำไหลบ่า ตะกอนที่ถูกกวน หรือการสะพรั่งของสาหร่าย',
    'param.turbidity.recommendation':
      'ตรวจสอบฝนที่ตกล่าสุดหรือการรบกวนทางต้นน้ำ หากค่ายังสูงอยู่ ให้ทำความสะอาดเลนส์เซนเซอร์',

    'param.tds.label': 'สารละลายทั้งหมด',
    'param.tds.fullName': 'สารละลายทั้งหมด (Total Dissolved Solids)',
    'param.tds.about':
      'สารละลายทั้งหมด (TDS) คือปริมาณแร่ธาตุและเกลือที่ละลายอยู่ในน้ำ วัดเป็นส่วนในล้านส่วน',
    'param.tds.impact':
      'TDS ที่อยู่นอกช่วงปกติอาจเปลี่ยนรสชาติของน้ำ บ่งชี้การปนเปื้อน หรือสร้างความเครียดให้สิ่งมีชีวิตน้ำจืด',
    'param.tds.recommendation':
      'เปรียบเทียบกับแนวโน้มล่าสุด หากค่าสูงผิดปกติ ให้ตรวจสอบน้ำไหลบ่าหรือการระบายน้ำในบริเวณใกล้เคียง',

    'param.ec.label': 'การนำไฟฟ้า',
    'param.ec.fullName': 'การนำไฟฟ้า (Electrical Conductivity)',
    'param.ec.about':
      'การนำไฟฟ้า (EC) เกิดจากไอออนที่ละลายอยู่ในน้ำ จึงแปรผันไปตาม TDS อย่างใกล้ชิด',
    'param.ec.impact':
      'ค่า EC ที่ผิดปกติหมายถึงเกลือหรือแร่ธาตุที่ละลายอยู่เปลี่ยนไป ซึ่งอาจบ่งชี้มลพิษหรือแร่ธาตุที่ไหลมากับน้ำ',
    'param.ec.recommendation':
      'ตรวจสอบค่า TDS ประกอบด้วย เพราะ EC คำนวณมาจากค่านั้น หากทั้งสองค่าเปลี่ยนกะทันหันควรตรวจสอบเพิ่มเติม',

    'param.flow.label': 'อัตราการไหล',
    'param.flow.about': 'อัตราการไหลของน้ำผ่านเซนเซอร์ ณ ขณะนั้น หน่วยเป็นลิตรต่อนาที',

    'unit.ntu.fullName': 'หน่วยวัดความขุ่นแบบเนฟีโลเมตริก (Nephelometric Turbidity Units)',
    'unit.ppm.fullName': 'ส่วนในล้านส่วน (parts per million)',
    'unit.ecUnit.fullName': 'ไมโครซีเมนส์ต่อเซนติเมตร (microsiemens per centimeter)',

    'detail.currentValue': 'ค่าปัจจุบัน',
    'detail.noRecord': 'ยังไม่มีข้อมูล',
    'detail.dataPoints': '{count} จุดข้อมูล',
    'detail.min': 'ต่ำสุด',
    'detail.avg': 'เฉลี่ย',
    'detail.max': 'สูงสุด',
    'detail.tooHigh': '{param} สูงกว่าช่วงปลอดภัย ({value} {unit})',
    'detail.tooLow': '{param} ต่ำกว่าช่วงปลอดภัย ({value} {unit})',
    'detail.checkSensor': 'ค่านี้ต่ำเกินกว่าจะเป็นจริง ควรตรวจสอบเซนเซอร์แทนที่จะตรวจคุณภาพน้ำ',
    'detail.normalRange': 'ช่วงปกติ: {range}',
    'detail.aboutTitle': 'เกี่ยวกับค่านี้',
    'detail.impactTitle': 'ผลกระทบ',
    'detail.recommendationTitle': 'ข้อแนะนำ',
    'detail.chartCaption': 'ข้อมูลจริงจากเซนเซอร์ เลือกช่วงเวลาได้ด้านบน',

    'wqi.title': 'ดัชนีคุณภาพน้ำ (WQI)',
    'wqi.moderate': 'ปานกลาง',
    'wqi.good': 'ดี',
    'wqi.poor': 'แย่',
    'wqi.unknown': 'ไม่ทราบ',
    'wqi.empty': 'ยังไม่มีข้อมูลย้อนหลังในช่วงเวลานี้',
    'wqi.error': 'โหลดข้อมูลย้อนหลังของช่วงเวลานี้ไม่สำเร็จ',

    'quickview.title': 'ภาพรวมด่วน',
    'quickview.sensorFault': 'เซนเซอร์ไม่เชื่อมต่อ',
    'quickview.analysis.noData': 'ยังไม่มีข้อมูลจากเซนเซอร์แบบสด',
    'quickview.analysis.good': 'ค่าทุกตัวอยู่ในช่วงปกติ',
    'quickview.analysis.watch': '{band} — ต้องเฝ้าระวัง: {params}',
    'quickview.analysis.fault': 'ควรตรวจสอบเซนเซอร์: {params} อาจไม่ได้เชื่อมต่อ',
    'quickview.flow.label': 'อัตราการไหลปัจจุบัน',
    'quickview.usage.label': 'ปริมาณการใช้น้ำวันนี้',

    'chart.flow.title': 'อัตราการไหลของน้ำ',
    'chart.flow.unit': 'ลิตร/นาที',
    'chart.usage.title': 'ปริมาณการใช้น้ำ',
    'chart.usage.unit': 'ลิตร',
    'chart.usage.today': 'วันนี้: {value} ลิตร',
    'chart.usage.empty': 'ยังไม่มีข้อมูลการใช้น้ำ',
    'chart.usage.resetToday': 'รีเซ็ตของวันนี้',
    'chart.usage.resetSuccess': 'รีเซ็ตปริมาณการใช้น้ำวันนี้แล้ว',
    'chart.usage.resetFailed': 'รีเซ็ตปริมาณการใช้น้ำวันนี้ไม่สำเร็จ',

    'calib.title': 'ปรับเทียบเซนเซอร์',
    'calib.subtitle': 'ปรับเทียบได้ขณะเซนเซอร์ทำงานอยู่ โดยไม่ต้องอัปโหลดเฟิร์มแวร์ใหม่',
    'calib.modeLabel': 'โหมดสอบเทียบ',
    'calib.modeOn': 'เปิด',
    'calib.modeOff': 'ปิด',
    'calib.applyingTurbidity': 'กำลังใช้ค่าสอบเทียบความขุ่น...',
    'calib.applyingTds': 'กำลังใช้ค่าสอบเทียบ TDS...',
    'calib.applyingFlow': 'กำลังใช้ค่าสอบเทียบอัตราการไหล...',
    'calib.failedTurbidity': 'ใช้ค่าสอบเทียบความขุ่นไม่สำเร็จ',
    'calib.failedTds': 'ใช้ค่าสอบเทียบ TDS ไม่สำเร็จ',
    'calib.failedFlow': 'ใช้ค่าสอบเทียบอัตราการไหลไม่สำเร็จ',
    'calib.resetSuccess': 'รีเซ็ตค่าสอบเทียบแล้ว',
    'calib.resetFailed': 'รีเซ็ตไม่สำเร็จ',
    'calib.modeChangeFailed': 'เปลี่ยนโหมดไม่สำเร็จ',
    'calib.temperatureTitle': 'อุณหภูมิ',
    'calib.noCalibrationNeeded': 'ไม่ต้องสอบเทียบ',
    'calib.factoryCalibrated': 'ปรับเทียบจากโรงงานแล้ว (DS18B20 ±0.5°C)',
    'calib.ecTitle': 'การนำไฟฟ้า (EC)',
    'calib.noSeparateSensor': 'ไม่มีเซนเซอร์แยก',
    'calib.derivedFromTds': 'คำนวณจาก TDS (×0.5) สอบเทียบผ่าน TDS',
    'calib.resetTurbidity': 'รีเซ็ตความขุ่น',
    'calib.resetTds': 'รีเซ็ต TDS',
    'calib.resetFlow': 'รีเซ็ตอัตราการไหล',
    'calib.flowFormTitle': 'สอบเทียบอัตราการไหล (ค่า k)',
    'calib.flowReferenceLabel': 'ปริมาตรที่ทราบค่า (ลิตร)',
    'calib.flowRawLabel': 'ค่าที่วัดได้ (จำนวนพัลส์)',
    'calib.flowRawHint': 'ปล่อยน้ำตามปริมาตรที่ทราบผ่านเซนเซอร์ แล้วกรอกจำนวนพัลส์ทั้งหมดที่นับได้',
    'calib.needFlowPoints': '1 จุด',
    'calib.flowKFactorFormula': 'ลิตร = พัลส์ ÷ k (k = พัลส์ต่อลิตร)',
    'calib.observedRange': 'ค่าที่พบระหว่างสอบเทียบ: ต่ำสุด {min}, สูงสุด {max}',
    'calib.useMin': 'ใช้ค่าต่ำสุด',
    'calib.useMax': 'ใช้ค่าสูงสุด',
    'calib.resetRange': 'รีเซ็ตช่วงค่า',
    'calib.loading': 'กำลังโหลด...',
    'calib.sensorSelectAria': 'เลือกเซนเซอร์',
    'calib.turbidityFormTitle': 'สอบเทียบความขุ่น (2 จุด)',
    'calib.turbidityReferenceLabel': 'ค่ามาตรฐาน (NTU)',
    'calib.turbidityRawLabel': 'ค่าที่วัดได้ (Raw ADC)',
    'calib.turbidityRawHint': 'เว้นว่างเพื่อใช้ค่าปัจจุบัน',
    'calib.tdsFormTitle': 'สอบเทียบ TDS (k-factor)',
    'calib.tdsReferenceLabel': 'ค่ามาตรฐาน (ppm)',
    'calib.tdsRawLabel': 'ค่าที่วัดได้ (ppm, ไม่บังคับ)',
    'calib.tdsRawHint':
      'ใช้ดูตัวอย่างเท่านั้น ไม่ส่งไปเซิร์ฟเวอร์ กรอกค่า ppm ที่ยังไม่ได้ปรับเทียบ ไม่ใช่แรงดันไฟ',
    'calib.applyLabel': 'ใช้ค่า',
    'calib.applying': 'กำลังบันทึก...',
    'calib.needTwoPoints': 'ต้องการ 2 จุด',
    'calib.singlePoint': 'จุดเดียว',
    'calib.liveReading': 'ค่าปัจจุบัน',
    'calib.pointLabel': 'จุดที่ {n}',
    'calib.savedPoints': 'จุดที่บันทึกแล้ว',
    'calib.deletePoint': 'ลบจุด',
    'calib.coefficientsTitle': 'ค่าสัมประสิทธิ์',
    'calib.pending': 'ยังไม่ยืนยัน',
    'calib.notCalibrated': 'ยังไม่ได้สอบเทียบ',
    'calib.needTurbidityPoints': '2 จุด',
    'calib.needTdsPoints': '1 จุด',
    'calib.currentResult': 'ผลลัพธ์ปัจจุบัน',
    'calib.kFactorFormula': 'ppm ที่ปรับเทียบ = k × ค่า TDS ดิบ',
    'calib.lastSaved': 'บันทึกล่าสุด',

    'history.title': 'ประวัติข้อมูล',
    'history.loading': 'กำลังโหลด...',
    'history.failed': 'โหลดข้อมูลไม่สำเร็จ',
    'history.empty': 'ไม่มีข้อมูลในช่วงเวลานี้',
    'history.exportCsv': 'ส่งออก CSV',
    'history.col.time': 'เวลา',
    'history.col.temperature': 'อุณหภูมิ (°C)',
    'history.col.turbidity': 'ความขุ่น',
    'history.col.tds': 'สารละลายทั้งหมด (ppm)',
    'history.col.ec': 'การนำไฟฟ้า (µS/cm)',
    'history.col.status': 'สถานะ',
    'history.rowCount': '{count} รายการ จาก {source}',
    'history.refreshing': 'กำลังรีเฟรช...',

    'common.close': 'ปิด',
    'common.reload': 'โหลดใหม่',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.openMenu': 'เปิดเมนู',
    'common.loading': 'กำลังโหลด...',
    'common.uncalibrated': 'ยังไม่สอบเทียบ (Raw ADC)',

    'theme.toggle': 'สลับธีม',
    'theme.label': 'ธีม',
    'theme.light': 'สว่าง',
    'theme.dark': 'มืด',

    'lang.switch': 'เปลี่ยนภาษา',
    'lang.en': 'English',
    'lang.th': 'ไทย',

    'tour.welcome.title': 'ยินดีต้อนรับสู่ Aqua Monitor',
    'tour.welcome.body': 'มาดูภาพรวมของแดชบอร์ดกันสักครู่ ใช้เวลาไม่นาน',
    'tour.navDashboard.title': 'แท็บแดชบอร์ด',
    'tour.navDashboard.body': 'ภาพรวมแบบสด ทั้งประวัติคุณภาพน้ำ ค่าปัจจุบัน และมาตรวัดความปลอดภัย',
    'tour.paramGrid.title': 'ค่าที่วัดได้แบบสด',
    'tour.paramGrid.body': 'อุณหภูมิ ความขุ่น TDS และ EC อัปเดตแบบเรียลไทม์ แตะที่การ์ดใดก็ได้เพื่อดูรายละเอียดและแนวโน้ม',
    'tour.quickView.title': 'ภาพรวมด่วน',
    'tour.quickView.body': 'สรุปดัชนีคุณภาพน้ำโดยรวมและสถานะของแต่ละพารามิเตอร์ในมุมมองเดียว',
    'tour.navCalibration.title': 'แท็บปรับเทียบ',
    'tour.navCalibration.body': 'ปรับเทียบเซนเซอร์ความขุ่นและ TDS กับตัวอย่างอ้างอิงที่ทราบค่า โดยไม่ต้องอัปโหลดเฟิร์มแวร์ใหม่',
    'tour.navHistory.title': 'แท็บประวัติ',
    'tour.navHistory.body': 'ดูข้อมูลย้อนหลังตามช่วงเวลาที่เลือก และส่งออกเป็นไฟล์ CSV',
    'tour.themeToggle.title': 'สลับธีม',
    'tour.themeToggle.body': 'สลับระหว่างโหมดสว่างและมืดได้ตลอดเวลา',
    'tour.langToggle.title': 'ภาษา',
    'tour.langToggle.body': 'สลับภาษาของทั้งอินเทอร์เฟซระหว่างอังกฤษและไทย',
    'tour.done.title': 'พร้อมใช้งานแล้ว',
    'tour.done.body': 'เล่นทัวร์นี้ซ้ำได้ทุกเมื่อจากปุ่มช่วยเหลือ ขอให้เพลิดเพลินกับการติดตามคุณภาพน้ำ',
    'tour.next': 'ถัดไป',
    'tour.back': 'ย้อนกลับ',
    'tour.skip': 'ข้าม',
    'tour.done': 'เสร็จสิ้น',
    'tour.stepCounter': '{current} / {total}',
    'tour.helpButtonAria': 'เล่นทัวร์แนะนำซ้ำ',
    'tour.helpLabel': 'ช่วยเหลือ',

    'notif.bellAria': 'ตั้งค่าการแจ้งเตือน',
    'notif.title': 'การแจ้งเตือน',
    'notif.description': 'รับการแจ้งเตือนเมื่อค่าที่วัดได้เข้าสู่ช่วงเฝ้าระวังหรืออันตราย แม้ปิดแท็บนี้อยู่',
    'notif.unsupported': 'เบราว์เซอร์นี้ไม่รองรับการแจ้งเตือนแบบพุช',
    'notif.insecureContext': 'การแจ้งเตือนแบบพุชต้องใช้การเชื่อมต่อที่ปลอดภัย (HTTPS หรือ localhost)',
    'notif.enable': 'เปิดใช้การแจ้งเตือน',
    'notif.enabling': 'กำลังเปิดใช้งาน...',
    'notif.unsubscribe': 'ยกเลิกการแจ้งเตือน',
    'notif.unsubscribing': 'กำลังยกเลิก...',
    'notif.prefsTitle': 'แจ้งเตือนเมื่อ',
    'notif.subscribeSuccess': 'เปิดใช้การแจ้งเตือนแล้ว',
    'notif.subscribeFailedPermission': 'สิทธิ์การแจ้งเตือนถูกปฏิเสธ',
    'notif.subscribeFailedUnavailable': 'เซิร์ฟเวอร์ยังไม่ได้ตั้งค่าการแจ้งเตือนแบบพุช',
    'notif.subscribeFailed': 'เปิดใช้การแจ้งเตือนไม่สำเร็จ',
    'notif.unsubscribeSuccess': 'ปิดการแจ้งเตือนแล้ว',
    'notif.unsubscribeFailed': 'ยกเลิกการแจ้งเตือนไม่สำเร็จ',
    'notif.prefsSaveFailed': 'บันทึกการตั้งค่าการแจ้งเตือนไม่สำเร็จ',
    'notif.sendTest': 'ส่งการแจ้งเตือนทดสอบ',
    'notif.sendingTest': 'กำลังส่ง...',
    'notif.testSuccess': 'ส่งการแจ้งเตือนทดสอบแล้ว',
    'notif.testFailed': 'ส่งการแจ้งเตือนทดสอบไม่สำเร็จ',

    'settings.bellAria': 'ตั้งค่า',
    'settings.title': 'ตั้งค่า',
    'settings.notificationsSection': 'การแจ้งเตือน',
    'settings.displaySection': 'การแสดงผลแดชบอร์ด',
    'settings.displayDescription': 'เลือกข้อมูลที่จะแสดงในแดชบอร์ดหลัก',
    'settings.showWaterUsage': 'กราฟการใช้น้ำ',

    'wifi.label': 'WiFi',
    'wifi.title': 'ตั้งค่า WiFi',
    'wifi.description': 'เชื่อมต่อ ESP32 กับเครือข่ายผ่าน USB โดยไม่ต้องอัปโหลดเฟิร์มแวร์ใหม่',
    'wifi.unsupportedBrowser': 'การเข้าถึงอุปกรณ์ USB ต้องใช้ Chrome, Edge หรือเบราว์เซอร์ที่ใช้ Chromium (เบราว์เซอร์นี้ไม่รองรับ)',
    'wifi.deviceConnect': 'เชื่อมต่อบอร์ด',
    'wifi.deviceConnecting': 'กำลังเชื่อมต่อ...',
    'wifi.deviceConnectHint': 'เบราว์เซอร์จะให้คุณเลือกพอร์ต USB ของบอร์ด',
    'wifi.deviceConnectFailed': 'เชื่อมต่อบอร์ดไม่สำเร็จ',
    'wifi.deviceDisconnect': 'ยกเลิกการเชื่อมต่อ',
    'wifi.deviceDisconnected': 'บอร์ดถูกตัดการเชื่อมต่อ',
    'wifi.notConnected': 'ยังไม่ได้เชื่อมต่อกับเครือข่ายใด',
    'wifi.currentlyConnected': 'เชื่อมต่อกับ {ssid} แล้ว ({ip})',
    'wifi.scan': 'ค้นหาเครือข่าย',
    'wifi.scanning': 'กำลังค้นหา...',
    'wifi.scanFailed': 'ค้นหาเครือข่ายไม่สำเร็จ',
    'wifi.noNetworks': 'ไม่พบเครือข่าย ลองค้นหาอีกครั้ง',
    'wifi.passwordLabel': 'รหัสผ่าน',
    'wifi.passwordPlaceholder': 'กรอกรหัสผ่านเครือข่าย',
    'wifi.connect': 'เชื่อมต่อ',
    'wifi.connecting': 'กำลังเชื่อมต่อ...',
    'wifi.connectSuccess': 'เชื่อมต่อสำเร็จ! IP ใหม่: {ip}',
    'wifi.connectFailed': 'เชื่อมต่อไม่สำเร็จ',
    'wifi.backendTitle': 'แบ็กเอนด์อยู่คนละเครือข่าย',
    'wifi.backendDescription':
      'โดยปกติบอร์ดจะค้นหาแบ็กเอนด์ด้วยการกระจายสัญญาณในเครือข่ายของตัวเอง ซึ่งใช้ได้เฉพาะเมื่อคอมพิวเตอร์แบ็กเอนด์อยู่เครือข่ายเดียวกัน หากอยู่คนละเครือข่าย ให้กรอกที่อยู่ของแบ็กเอนด์ที่นี่ (โฮสต์เนมหรือ IP ที่เข้าถึงได้จากอินเทอร์เน็ตหรือ VPN เช่นชื่อ DDNS) เพื่อให้บอร์ดเชื่อมต่อโดยตรง',
    'wifi.backendCurrentFixed': 'กำลังใช้แบ็กเอนด์คงที่: {host}',
    'wifi.backendCurrentAuto': 'กำลังใช้การค้นหาอัตโนมัติในเครือข่ายเดียวกัน',
    'wifi.backendHttpsOn': 'HTTPS',
    'wifi.backendKeySet': 'ตั้งค่า API key แล้ว',
    'wifi.backendHostLabel': 'โฮสต์หรือ IP ของแบ็กเอนด์',
    'wifi.backendHostPlaceholder': 'เช่น myhydro.duckdns.org',
    'wifi.backendApiKeyLabel': 'API key (ไม่บังคับ)',
    'wifi.backendApiKeyPlaceholder': 'เว้นว่างไว้หากไม่ต้องการยืนยันตัวตน',
    'wifi.backendApiKeyHint':
      'ต้องตรงกับ updateApiKey ใน webconfig.json ของแบ็กเอนด์ จำเป็นเมื่อแบ็กเอนด์เข้าถึงได้จากนอกเครือข่ายท้องถิ่น มิฉะนั้นใครก็ตามที่เข้าถึงได้จะส่งข้อมูลปลอมเข้ามาได้',
    'wifi.backendHttpsLabel': 'ใช้ HTTPS (แนะนำเมื่ออยู่นอกเครือข่ายท้องถิ่น)',
    'wifi.backendSave': 'บันทึก',
    'wifi.backendSaving': 'กำลังบันทึก...',
    'wifi.backendClear': 'ล้างค่า (ใช้การค้นหาอัตโนมัติ)',
    'wifi.backendSaveSuccess': 'อัปเดตแบ็กเอนด์แล้ว',
    'wifi.backendSaveFailed': 'อัปเดตแบ็กเอนด์ไม่สำเร็จ',
    'wifi.backendTest': 'ทดสอบการเชื่อมต่อ',
    'wifi.backendTesting': 'กำลังทดสอบ...',
    'wifi.backendTestSuccess': 'เชื่อมต่อสำเร็จ ({detail})',
    'wifi.backendTestUnreachable': 'เชื่อมต่อแบ็กเอนด์ไม่ได้',
    'wifi.backendTestFailed': 'ทดสอบไม่สำเร็จ',
    'wifi.stationTitle': 'ชื่อสถานี',
    'wifi.stationDescription':
      'ป้ายชื่อสั้น ๆ สำหรับบอร์ดนี้ (เช่น "ทางเข้า" หรือ "ทางออก") เพื่อให้แดชบอร์ดแยกแยะหลายบอร์ดได้ หากมีบอร์ดเดียวไม่จำเป็นต้องตั้งค่า',
    'wifi.stationCurrentSet': 'บอร์ดนี้ตั้งชื่อว่า: {name}',
    'wifi.stationCurrentUnset': 'ยังไม่ได้ตั้งชื่อสถานี (จะรายงานเป็นสถานีหลัก)',
    'wifi.stationLabel': 'ชื่อสถานี',
    'wifi.stationPlaceholder': 'เช่น ทางเข้า',
    'wifi.stationSave': 'บันทึก',
    'wifi.stationSaving': 'กำลังบันทึก...',
    'wifi.stationClear': 'ล้างค่า',
    'wifi.stationSaveSuccess': 'อัปเดตชื่อสถานีแล้ว',
    'wifi.stationSaveFailed': 'อัปเดตชื่อสถานีไม่สำเร็จ',
  } satisfies Record<keyof typeof en, string>,
} as const

export type MessageKey = keyof typeof messages.en
